name: ali_mount_project
description: 阿里山貴賓館
publish_to: 'none'

version: 1.6.0+11

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/texture/icon.png"
  min_sdk_android: 19
  windows:
    generate: true
    image_path: "assets/texture/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/texture/icon.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/texture/
    - assets/texture/west/
    - assets/texture/east/
    - assets/voice/west/
    - assets/voice/east/
